sudo: false

language: node_js
node_js:
    - "12"
    - "10"
    - "8"

script:
    - npm run coverage

notifications:
    email: false
    webhooks:
        - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
